git[hooks]: Add Git LFS hooks
Git LFS uses `post-checkout`, `post-commit`, `post-merge` and `pre-push`
hooks. We add those in this commit.

diff --git a/git/hooks/pre-push b/git/hooks/pre-push
--- a/git/hooks/pre-push
+++ b/git/hooks/pre-push
@@ -1,5 +1,17 @@
 #!/usr/bin/env bash
 
+
+# Capture stdin to allow replaying it to both `git lfs pre-push` and our own pre-push logic
+input_file="$(mktemp)"
+trap 'rm -f "$input_file"' EXIT
+cat >"$input_file"
+
+### git lfs BEGIN ###
+# This is the default/automatic `git lfs` hook
+command -v git-lfs >/dev/null 2>&1 || { printf >&2 "\n%s\n\n" "This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'pre-push' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks')."; exit 2; }
+git lfs pre-push "$@" <"$input_file"
+### git lfs END ###
+
 # Pre-push hook to prevent pushing commits with:
 # - Commit messages starting with "!"
 # - Commit messages containing "WIP" (case-insensitive)
@@ -16,7 +28,7 @@ GIT_DIR="$GIT_REPO_DIR_ABSOLUTE/$GIT_DOT_DIR_RELATIVE"
 GIT_DIR="$GIT_DOT_DIR_RELATIVE"
 
 if [ -f "$GIT_DIR/hooks/pre-push" ]; then
-    "$GIT_DIR/hooks/pre-push"
+    "$GIT_DIR/hooks/pre-push" <"$input_file"
 fi
 
 # Read stdin to get the list of commits being pushed
@@ -84,6 +96,6 @@ while read local_ref local_sha remote_ref remote_sha; do
             exit 1
         fi
     done
-done
+done <"$input_file"
 
 exit 0
